# Generated by Django 4.2.4 on 2023-09-15 01:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=500)),
                ('data', models.DateTimeField(default=datetime.datetime(2023, 9, 14, 22, 32, 58, 757147))),
            ],
        ),
        migrations.CreateModel(
            name='Equipamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('descricao', models.CharField(max_length=500)),
                ('foto', models.CharField(max_length=500)),
                ('data', models.DateTimeField(default=datetime.datetime(2023, 9, 14, 22, 32, 58, 757147))),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('senha', models.DecimalField(decimal_places=2, max_digits=30)),
                ('cargo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Relacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentario', to='Senai_Equipamentos.comentarios')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipamento', to='Senai_Equipamentos.equipamentos')),
            ],
        ),
        migrations.AddField(
            model_name='comentarios',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='Senai_Equipamentos.users'),
        ),
    ]
